wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    framework: huggingface
    huggingface_version: 4.21.3
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.16
    start_time: 1688758370.877418
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      2:
      - 1
      - 11
      - 49
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.9.16
      5: 0.13.4
      6: 4.21.3
      8:
      - 1
      - 5
architecture:
  desc: null
  value: BERT
batch_size:
  desc: null
  value: 64
embedding_dimensions:
  desc: null
  value: 100
epochs:
  desc: null
  value: 10
learning_rate:
  desc: null
  value: 0.01
