wandb_version: 1

learning_rate:
  desc: null
  value: 1.0e-05
architecture:
  desc: null
  value: BERT
batch_size:
  desc: null
  value: 64
epochs:
  desc: null
  value: 500
embedding_dimensions:
  desc: null
  value: 64
_wandb:
  desc: null
  value:
    python_version: 3.11.2
    cli_version: 0.15.8
    framework: huggingface
    huggingface_version: 4.27.4
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1692663826.511159
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.11.2
      5: 0.15.8
      6: 4.27.4
      8:
      - 1
      - 4
      - 5
