wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.2
    cli_version: 0.15.8
    framework: huggingface
    huggingface_version: 4.27.4
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1692653459.964453
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      2:
      - 1
      - 11
      - 49
      - 55
      3:
      - 2
      - 23
      4: 3.11.2
      5: 0.15.8
      6: 4.27.4
      8:
      - 1
      - 4
      - 5
